const baseColor = "#ffffff"
export const proseWhite = {
  white: {
    css: {
      '--tw-prose-body': `${baseColor} !important`,
      '--tw-prose-headings': `${baseColor} !important`,
      '--tw-prose-lead': `${baseColor} !important`,
      '--tw-prose-links': `${baseColor} !important`,
      '--tw-prose-bold': `${baseColor} !important`,
      '--tw-prose-counters': `${baseColor} !important`,
      '--tw-prose-bullets': `${baseColor} !important`,
      '--tw-prose-hr': `${baseColor} !important`,
      '--tw-prose-quotes': `${baseColor} !important`,
      '--tw-prose-quote-borders': `${baseColor} !important`,
      '--tw-prose-captions': `${baseColor} !important`,
      '--tw-prose-code': `${baseColor} !important`,
      '--tw-prose-pre-code': `${baseColor} !important`,
      '--tw-prose-pre-bg': `${baseColor} !important`,
      '--tw-prose-th-borders': `${baseColor} !important`,
      '--tw-prose-td-borders': `${baseColor} !important`,
      '--tw-prose-invert-body': `${baseColor} !important`,
      '--tw-prose-invert-headings': `${baseColor} !important`,
      '--tw-prose-invert-lead': `${baseColor} !important`,
      '--tw-prose-invert-links': `${baseColor} !important`,
      '--tw-prose-invert-bold': `${baseColor} !important`,
      '--tw-prose-invert-counters': `${baseColor} !important`,
      '--tw-prose-invert-bullets': `${baseColor} !important`,
      '--tw-prose-invert-hr': `${baseColor} !important`,
      '--tw-prose-invert-quotes': `${baseColor} !important`,
      '--tw-prose-invert-quote-borders': `${baseColor} !important`,
      '--tw-prose-invert-captions': `${baseColor} !important`,
      '--tw-prose-invert-code': `${baseColor} !important`,
      '--tw-prose-invert-pre-code': `${baseColor} !important`,
      '--tw-prose-invert-pre-bg': 'rgb(255 255 255 / 50%)',
      '--tw-prose-invert-th-borders': `${baseColor} !important`,
      '--tw-prose-invert-td-borders': `${baseColor} !important`,
    },
  },
}