import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SpaceTravel from "./SpaceTravel";
import "./globals.css";
import Header from "./components/Header";
import Container from "./components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-white`}>
        <SpaceTravel />
        <Header />
        <div className="relative z-10">
          <Container>{children}</Container>
        </div>
      </body>
    </html>
  );
}
