import type { Metadata } from "next";
import { Inter, Barlow } from "next/font/google";
import SpaceTravel from "./SpaceTravel";
import "./globals.css";
import Header from "./components/Header";
import Container from "./components/Container";
import type { Viewport } from 'next'
import Footer from "./components/Footer";
 
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

const barlow = Barlow({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.className} text-white`}>
        <SpaceTravel />
        <Header />
        <div className="relative z-10">
          <Container>{children}</Container>
        </div>
        <Footer />
      </body>
    </html>
  );
}
